export const REWARD_TYPES_MAP = {
  INVITATION_BONUS: "INVITATION BONUS",
  SIGNUP_BONUS: "SIGNUP BONUS",
  ATTENDANCE_BONUS: "ATTENDANCE BONUS",
  FIRST_RECHARGE_BONUS: "FIRST RECHARGE BONUS",
  DAILY_RECHARGE_BONUS: "DAILY RECHARGE BONUS",
  FIRST_RECHARGE_AGENT_BONUS: "FIRST RECHARGE AGENT BONUS",
  DAILY_RECHARGE_AGENT_BONUS: "DAILY RECHARGE AGENT BONUS",
  VIP_LEVEL_UP_BONUS: "VIP LEVEL UP BONUS",
  VIP_MONTHLY_REWARD: "VIP MONTHLY REWARD",
};

export const REWARD_STATUS_TYPES_MAP = {
  SUCCESS: 1,
  LOCKED: 2,
};
